services:
  app:
    build:
      context: .
      args:
        IMAGE: ghcr.io/nationalarchives/tna-python-dev
        IMAGE_TAG: preview
    environment:
      - ENVIRONMENT_NAME=localhost
      - CONFIG=config.Develop
      - BUILD_VERSION=local
      - DEBUG=true
      - SECRET_KEY=abc123
      - NPM_DEVELOP_COMMAND=dev
      - COOKIE_DOMAIN=localhost
      - SESSION_REDIS_URL=redis://redis:6379/0
      - RATELIMIT_REDIS_URL=redis://redis:6379/1
      - CSP_STYLE_SRC='sha256-pg+oQARqMq4wCazyrsMt8HY89BJkXkEFkwNWxg2iPdg='
      - ALTCHA_HMAC_KEY=abc123
      - CACHE_TYPE=RedisCache
      - CACHE_REDIS_URL=redis://redis:6379/2
      - SESSION_COOKIE_SECURE=False
      # - RATELIMIT_DEFAULT=5 per 5 seconds
      - ROSETTA_API_URL=https://rosetta-dev.k-int.com/rosetta/data
      - AWS_REGION=aws-ses-v2-local
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - SES_ENDPOINT=http://ses:8005
      - DEFAULT_INBOX=DEFAULT_INBOX@nationalarchives.gov.uk
      - FORM_REPORT_A_CATALOGUE_ISSUE_DIGITAL_DOWNLOADS_INBOX=DIGITAL_DOWNLOADS_INBOX@nationalarchives.gov.uk
      - FORM_REPORT_A_CATALOGUE_ISSUE_DIGITAL_PRESERVATION_INBOX=DIGITAL_PRESERVATION_INBOX@nationalarchives.gov.uk
      - FORM_REPORT_A_CATALOGUE_ISSUE_FINDING_ARCHIVES_PROJECT_INBOX=FINDING_ARCHIVES_PROJECT_INBOX@nationalarchives.gov.uk
      - FORM_REPORT_A_CATALOGUE_ISSUE_CATALOGUE_AMENDMENTS_INBOX=CATALOGUE_AMENDMENTS_INBOX@nationalarchives.gov.uk
    ports:
      - 65514:8080
    volumes:
      - ./:/app
    depends_on:
      - redis
      - ses
    healthcheck:
      start_period: 10s
      start_interval: 2s

  redis:
    image: redis:latest

  ses:
    image: ghcr.io/domdomegg/aws-ses-v2-local
    ports:
      - 65512:8005

  docs:
    image: squidfunk/mkdocs-material
    volumes:
      - .:/docs
    ports:
      - 65513:8000
