site_name: DS Forms Docs
repo_url: https://github.com/nationalarchives/ds-forms
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
