startingPage:
  id: start
  name: Apply to film at The National Archives
  content:
    description: Use this form if you are a member of the press and would like to apply to film or record inside The National Archives’ building.
    body: |
      <p>Please apply at least <strong>10 working days</strong> in advance and read the <a href="./details/">terms and conditions</a> before you apply.</p>
      <p>Submitting this form does not secure permission for filming. We will contact you via email to let you know when permission has been granted.</p>
    startButtonText: Start an application
    startButtonPage: your_details
  template: forms/landing.html

pages:
  - id: details
    name: Terms and conditions for filming at The National Archives
    slug: details
    template: forms/apply_to_film/details.html

  - id: your_details
    name: Your details
    slug: your-details
    content:
      supertitle: Page 1 of 2
      description: Tell us about you.
    form: apply_to_film.YourDetailsForm
    redirectWhenComplete:
      - page: about

  - id: about
    name: About your project
    slug: about-your-project
    content:
      supertitle: Page 2 of 2
      beforeSubmit: |
        <p><a href="https://www.nationalarchives.gov.uk/documents/filming-terms-and-conditions.pdf">Filming terms and conditions</a>.</p>
    form: apply_to_film.ProjectForm
    requires:
      - your_details
    redirectWhenComplete:
      - page: confirmation

  - id: confirmation
    name: Confirmation
    slug: confirmation
    template: forms/apply_to_film/confirmation.html
    form: ConfirmationForm
    # altcha: true
    requires:
      - your_details
      - about
    redirectWhenComplete:
      - page: final_page

finalPage:
  id: final_page
  name: Thank you
  slug: complete
  content:
    description: Thank you for contacting The National Archives with your application to film or record here.
    body: |
      <p>Thank you for completing the form. We will be in touch shortly.</p>
  template: forms/final.html
  requires:
    - your_details
    - about
    - confirmation
  redirectIfNotComplete: start
  resultHandlers:
    - type: email
      details:
        # process:
        #   template: outputs/example-email.jinja2
        send:
          from: systems.development@nationalarchives.gov.uk
          to: Andrew.Hosgood@nationalarchives.gov.uk
          subject: New Form Submission (original)
    - type: email
      details:
        # process:
        #   template: outputs/example-email.jinja2
        send:
          from: systems.development@nationalarchives.gov.uk
          toVar: your_details.email_address
          subject: New Form Submission (acknowledgement)
