meta:
  exclude_from_sitemap: true

startingPage:
  id: info
  name: Report an issue with the catalogue
  form: CatalogueIssue
  template: forms/catalogue_issue.html
  # altcha: true
  content:
    supertitle: Catalogue
    # description: Report an issue with the catalogue.
    # body: |
    #   <p>Completing this form should provide you with a simple email receipt.</p>
    breadcrumbs:
      items:
        - text: Home
          href: /
        - text: Catalogue
          href: /catalogue/
  redirectWhenComplete:
    - page: final_page

finalPage:
  id: final_page
  name: Thank you
  slug: complete
  content:
    panelTitle: Your issue has been submitted
    panelText: Your reference number is {{ completion_result_first_id }}.
    body: |
      <p>Thank you for taking the time to help us improve the catalogue. We may contact you within the next 10 days if we need further information. We will not be able to notify you if your suggestion is successful. This is due to the high volume of suggestions we receive.</p>
  template: forms/final.html
  requires:
    - info
  resultHandlers:
    # - type: email
    #   details:
    #     process:
    #       template: outputs/email.html
    #       panel:
    #         title: Application received
    #         body: <p>Your application has been received and is being processed.</p><p>Your reference number is <strong>{{ reference_number }}</strong>.</p>
    #       content: <p>TEST EMAIL</p><p>Filled out by {{ responses.info.reporter.email_address or 'anonymous user' }}</p>
    #       signoff: <p>Kind regards,</p><p>The team</p>
    #     send:
    #       toConfigVar: FORM_REPORT_A_CATALOGUE_ISSUE_INBOX
    #       subject: An issue has been reported with the catalogue
    - type: email
      details:
        process:
          template: outputs/email_json_dump.html
        send:
          toFunction: app.forms.lib.catalogue_issue.report_catalogue_issue_email
          subject: An issue has been reported with the catalogue (JSON dump)
