meta:
  exclude_from_sitemap: true

startingPage:
  id: info
  name: Report an issue with the catalogue
  form: CatalogueIssue
  template: forms/catalogue_issue.html
  # altcha: true
  content:
    supertitle: Catalogue
    # description: Report an issue with the catalogue.
    # body: |
    #   <p>Completing this form should provide you with a simple email receipt.</p>
    breadcrumbs:
      items:
        - text: Home
          href: /
        - text: Catalogue
          href: /catalogue/
  redirectWhenComplete:
    - page: final_page

finalPage:
  id: final_page
  name: Thank you
  slug: complete
  content:
    panelTitle: Your issue has been submitted
    panelText: Your reference number is {{ completion_result_first_id }}.
    body: |
      <p>Thank you for taking the time to help us improve the catalogue. We may contact you within the next 10 days if we need further information. We will not be able to notify you if your suggestion is successful. This is due to the high volume of suggestions we receive.</p>
  template: forms/final.html
  requires:
    - info
  resultHandlers:
    - type: email
      details:
        process:
          template: outputs/email_json_dump.html
        send:
          toFunction: app.forms.lib.catalogue_issue.report_catalogue_issue_email
          subject: An issue has been reported with the catalogue (JSON dump)
    - type: email
      details:
        process:
          template: outputs/email.html
          panel:
            title: Catalogue issue reported
            body: <p>An issue has been raised for the record <strong>{{ info.record_iaid }}</strong>.</p>
          content: |
            <dl class="tna-dl">
              <dt>IAID</dt>
              <dd>{{ info.record_iaid }}</dd>
              <dt>Error</dt>
              <dd>{{ info.error_details.error }}</dd>
              <dt>Expected</dt>
              <dd>{{ info.error_details.expected }}</dd>
              <dt>Additional information</dt>
              <dd>{{ info.error_details.additional_information or '<not given>' }}</dd>
              <dt>Reporter name</dt>
              <dd>{{ info.reporter.name or '<not given>' }}</dd>
              <dt>Reporter email</dt>
              <dd>{{ info.reporter.email or '<not given>' }}</dd>
            </dl>
          ctaButtons:
            - text: View the record
              href: https://beta.nationalarchives.gov.uk/catalogue/id/{{ info.record_iaid }}/
        send:
          toFunction: app.forms.lib.catalogue_issue.report_catalogue_issue_email
          subject: An issue has been reported with the catalogue
